verbatim:
  cabal-version: 2.2

name: uvmhs
version: 0.0.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-orphans
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings
  - -O2
  - -optP-Wno-nonportable-include-path

dependencies: 
  - array
  - base
  - bytestring
  - containers
  - directory
  - ghc-prim
  - process
  - repa
  - template-haskell
  - text
  - time

library:
  source-dirs: src

executable:
  source-dirs: main
  main: Main.hs
  dependencies: uvmhs
